apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
    - path: /usr/bin/curl
    - path: /usr/bin/wget
  file:
    matchDirectories:
    - dir: /etc/
      recursive: true
    - dir: /var/
      recursive: true
  action: Block
  severity: 5
  message: "Blocked unauthorized process or file access by Wisecow pod"
