apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-external-access
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
    - path: /usr/bin/curl
  action: Block
  severity: 5
  message: "Outbound curl blocked by zero-trust policy"
